# Generated by Django 3.0.2 on 2020-04-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin_no', models.IntegerField()),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_allmodel_vendor_related', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_allmodel_vendor_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('tax_name', models.CharField(max_length=20)),
                ('tax_percentage', models.CharField(max_length=3)),
                ('cgsct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sgsct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('igsct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_allmodel_tax_related', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_allmodel_tax_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('product_code', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=500)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_allmodel_product_related', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_allmodel_product_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('website_name', models.URLField(blank=True, max_length=36, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=60, null=True)),
                ('gst_in', models.CharField(blank=True, max_length=60, null=True)),
                ('cin', models.CharField(blank=True, max_length=60, null=True)),
                ('adress', models.TextField(max_length=250)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin_no', models.IntegerField()),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_allmodel_company_related', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_allmodel_company_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin_no', models.IntegerField()),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_allmodel_client_related', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_allmodel_client_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
