# Generated by Django 2.2 on 2020-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmodel', '0002_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
