# Generated by Django 2.2 on 2020-04-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allmodel', '0002_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
